#!/usr/bin/env bash

case "$1" in
    lock)
	betterlockscreen -l dimblur -t "Hello "$USER"!"
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        betterlockscreen -s dimblur -t "Hello "$USER"!"
        ;;
    hibernate)
        betterlockscreen -l dimblur -t "Hello "$USER"!" & systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0

