#!/bin/zsh

case "$1" in
	"a") char="ä" ;;
	"o") char="ö" ;;
	"u") char="ü" ;;
	"A") char="Ä" ;;
	"O") char="Ö" ;;
	"U") char="Ü" ;;
	"ss") char="ß" ;;
	"SS") char="ẞ" ;;
	*) 
		echo "Usage: $0 [a|o|u|A|O|U|ss|SS]"
    exit 2
esac

echo $char | xclip -selection "clipboard"
